version: '2'
services:
  myigniter:
    build: .
    image: mobibgo
    volumes:
      - .:/var/www/html
      - ./myigniter-apache.conf:/etc/apache2/sites-enabled/myigniter-apache.conf
      - /var/www/html/node_modules
    ports:
      - "8084:80"
    depends_on:
      - myigniter-mysql
    links:
        - redis
  myigniter-mysql:
    image: mysql:5
    volumes:
      - .mysql-data:/var/lib/mysql    
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myigniter
  memcached:
    image: memcached
    ports:
      - "11212:11211"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - myigniter-mysql:myigniter-mysql
        ports:
            - 8000:80
        environment:
            MYSQL_HOST: myigniter-mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: myigniter-mysql
            USER: root